<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-02-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('illustration', models.ImageField(upload_to='')),
                ('quantity', models.PositiveIntegerField()),
                ('genre', models.CharField(choices=[('Comedy', 'Comedy'), ('Fantastic', 'Fantastic'), ('Terrible', 'Terrible'), ('Romantic', 'Romantic'), ('Drama', 'Drama'), ('Action', 'Action'), ('Education', 'Education')], max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
=======
# Generated by Django 4.0.2 on 2022-02-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('illustration', models.ImageField(upload_to='')),
                ('quantity', models.PositiveIntegerField()),
                ('genre', models.CharField(choices=[('Comedy', 'Comedy'), ('Fantastic', 'Fantastic'), ('Terrible', 'Terrible'), ('Romantic', 'Romantic'), ('Drama', 'Drama'), ('Action', 'Action'), ('Education', 'Education')], max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
>>>>>>> 26b57527738a8bfd7887a36dba9594230e45ac9d
