# Generated by Django 4.0.2 on 2022-02-25 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Film',
            new_name='Cinema',
        ),
    ]
