# Generated by Django 4.0.2 on 2022-02-10 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('serials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_comment', to='serial.serial')),
            ],
        ),
    ]
